#!/bin/bash
set -e
cat <<EOT >> /home/tooloop/.config/openbox/autostart

# Virtual Keyboard
# set keyboard layout"
# https://answers.launchpad.net/onboard/+question/235265
/home/tooloop/.config/onboard/onboard-config.sh &
onboard &
EOT

exit 0
